# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20161224_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails'),
        ),
    ]
