# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_photo_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name='thumbnail',
            table='thumbnail',
        ),
    ]
