# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20161225_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='thumbnail'),
        ),
    ]
