# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20161226_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=False, upload_to=photos.models.get_path_for_my_model_file),
        ),
    ]
