# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20170105_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='thumbnail/'),
        ),
        migrations.DeleteModel(
            name='ThumbNail',
        ),
    ]
