# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20170105_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=False, max_length=500, upload_to=photos.models.get_path_for_my_model_file),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(editable=False, max_length=500, null=True, upload_to='thumbnail/'),
        ),
    ]
