# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20170107_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=False, max_length=10000, upload_to=photos.models.get_path_for_my_model_file),
        ),
    ]
